// Outlines the public mark (D-41) in Space Mono Bold and writes the logo SVGs to assets/.
//
// - Wordmark: "SYNTHWERK." in capitals, tracking -4 %, like the overview repo banners
//   (synthwerk/scripts/make-banner.py) and velimir-mueller.de.
// - Mark: "S." on a rounded square tile, for favicons and app icons.
// - Lockup ("logo"): the mark left of the wordmark.
// - Font: SpaceMono-Bold.ttf from the official google/fonts repo, pinned in scripts/fonts.ts.
// - Licence: SIL OFL 1.1. The font file stays in .cache/ (git-ignored). Only the outlined paths
//   go into the SVGs; the OFL allows this (artwork made with the font is not Font Software).
//
// Run: pnpm --filter @synthwerk/tokens wordmark   (needs network on the first run)
import { mkdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import opentype, { type Font } from 'opentype.js'
import { type Primitive, primitives } from '../src/tokens.ts'
import { fetchPinned } from './fonts.ts'

const assetsDir = fileURLToPath(new URL('../assets/', import.meta.url))

const hex = (p: Primitive): string => primitives[p]

interface Palette {
  /** Wordmark colour. */
  readonly ink: string
  /** Tile of the mark. */
  readonly tile: string
  /** Letters on the tile. */
  readonly onTile: string
}

const palettes: Record<'light' | 'dark', Palette> = {
  // Light surfaces: ink wordmark, ink tile (like the "VM" badge on velimir-mueller.de).
  light: { ink: hex('zinc-850'), tile: hex('zinc-850'), onTile: hex('zinc-50') },
  // Dark surfaces: paper wordmark, paper tile (like the white pill CTA).
  dark: { ink: hex('zinc-50'), tile: hex('zinc-50'), onTile: hex('graphite-950') }
}

interface Box {
  x1: number
  y1: number
  x2: number
  y2: number
}

/** Outlines `text` with the baseline at (x, y). Tracking in em. Returns path data and box. */
function outline(
  font: Font,
  text: string,
  size: number,
  x: number,
  y: number,
  trackingEm: number
): { d: string; box: Box } {
  // Glyph by glyph: opentype.js 2.0.0 writes NaN into the path data with `letterSpacing`,
  // and its shaper (stringToGlyphs) fails on the Space Mono `ccmp` lookups. Capitals need no shaping.
  const scale = size / font.unitsPerEm
  const glyphs = [...text].map((ch) => font.charToGlyph(ch))
  const parts: string[] = []
  const box: Box = { x1: Infinity, y1: Infinity, x2: -Infinity, y2: -Infinity }
  let cx = x
  glyphs.forEach((glyph, i) => {
    const p = glyph.getPath(cx, y, size, {}, font)
    parts.push(p.toPathData(2))
    const b = p.getBoundingBox()
    box.x1 = Math.min(box.x1, b.x1)
    box.y1 = Math.min(box.y1, b.y1)
    box.x2 = Math.max(box.x2, b.x2)
    box.y2 = Math.max(box.y2, b.y2)
    const next = glyphs[i + 1]
    const kern = next ? font.getKerningValue(glyph, next) : 0
    cx += (glyph.advanceWidth + kern) * scale + trackingEm * size
  })
  const d = parts.join('')
  if (!/^[MLQCZ0-9 .-]+$/.test(d)) throw new Error(`Path data for "${text}" is not finite`)
  return { d, box }
}

const round = (n: number): number => Math.round(n * 100) / 100

const header = (comment: string): string =>
  `<!-- ${comment} Generated by packages/tokens/scripts/outline-wordmark.ts. Do not edit. -->\n`

const svg = (w: number, h: number, viewBox: string, body: string, comment: string): string =>
  `${header(comment)}<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${w}" height="${h}" role="img" aria-label="SYNTHWERK."><title>synthwerk</title>${body}</svg>\n`

const WORD = 'SYNTHWERK.'
const MONO = 'S.'
const TRACKING = -0.04
const TILE = 48
const TILE_RADIUS = 11

async function main(): Promise<void> {
  const ttf = await fetchPinned('spacemono', 'SpaceMono-Bold.ttf')
  await fetchPinned('spacemono', 'OFL.txt')
  const font = opentype.parse(new Uint8Array(ttf).buffer)
  const credit = 'Text outlined from Space Mono Bold (SIL OFL 1.1, The Space Mono Project Authors).'

  // Mark: "S." centred on the 48 px tile by its outline box (optical centre, not advance width).
  const markSize = 30
  const probe = outline(font, MONO, markSize, 0, 0, -0.06)
  const mx = (TILE - (probe.box.x2 - probe.box.x1)) / 2 - probe.box.x1
  const my = (TILE - (probe.box.y2 - probe.box.y1)) / 2 - probe.box.y1
  const mark = outline(font, MONO, markSize, round(mx), round(my), -0.06)

  // Wordmark: cap height 26 px (Space Mono cap height = 0.70 em).
  const wordSize = 37
  const baseline = 45
  const wordProbe = outline(font, WORD, wordSize, 0, baseline, TRACKING)
  const lockupX = TILE + 16 - wordProbe.box.x1
  const lockupWord = outline(font, WORD, wordSize, lockupX, baseline, TRACKING)
  const lockupW = Math.ceil(lockupWord.box.x2) + 2

  mkdirSync(assetsDir, { recursive: true })
  const tile = (p: Palette, x = 0, y = 0): string =>
    `<rect x="${x}" y="${y}" width="${TILE}" height="${TILE}" rx="${TILE_RADIUS}" fill="${p.tile}"/>`

  for (const [mode, p] of Object.entries(palettes)) {
    // Lockup: tile and wordmark, 64 px high.
    writeFileSync(
      `${assetsDir}synthwerk-logo-${mode}.svg`,
      svg(
        lockupW,
        64,
        `0 0 ${lockupW} 64`,
        `<g transform="translate(0 8)">${tile(p)}<path fill="${p.onTile}" d="${mark.d}"/></g><path fill="${p.ink}" d="${lockupWord.d}"/>`,
        `SYNTHWERK. lockup, ${mode} surfaces. ${credit}`
      )
    )
    // Wordmark only, tight box with 2 px padding.
    const b = wordProbe.box
    const pad = 2
    const x = Math.floor(b.x1) - pad
    const y = Math.floor(b.y1) - pad
    const w = Math.ceil(b.x2) + pad - x
    const h = Math.ceil(b.y2) + pad - y
    writeFileSync(
      `${assetsDir}synthwerk-wordmark-${mode}.svg`,
      svg(
        w,
        h,
        `${x} ${y} ${w} ${h}`,
        `<path fill="${p.ink}" d="${wordProbe.d}"/>`,
        `SYNTHWERK. wordmark, ${mode} surfaces. ${credit}`
      )
    )
    // Mark only, 48 px tile.
    writeFileSync(
      `${assetsDir}synthwerk-mark-${mode}.svg`,
      svg(
        TILE,
        TILE,
        `0 0 ${TILE} ${TILE}`,
        `${tile(p)}<path fill="${p.onTile}" d="${mark.d}"/>`,
        `S. mark, ${mode} surfaces. ${credit}`
      )
    )
  }

  // Favicon: one file that follows the browser colour scheme.
  const { light, dark } = palettes
  writeFileSync(
    `${assetsDir}synthwerk-favicon.svg`,
    svg(
      TILE,
      TILE,
      `0 0 ${TILE} ${TILE}`,
      `<style>.t{fill:${light.tile}}.l{fill:${light.onTile}}@media (prefers-color-scheme: dark){.t{fill:${dark.tile}}.l{fill:${dark.onTile}}}</style><rect class="t" width="${TILE}" height="${TILE}" rx="${TILE_RADIUS}"/><path class="l" d="${mark.d}"/>`,
      `S. favicon, follows prefers-color-scheme. ${credit}`
    )
  )
  console.log(
    `assets written. Lockup ${lockupW} × 64, wordmark box x ${wordProbe.box.x1.toFixed(1)}–${wordProbe.box.x2.toFixed(1)}`
  )
}

await main()
