// Outlines the "synthwerk" wordmark in Space Grotesk Bold and writes the logo SVGs to assets/.
//
// - Font: SpaceGrotesk[wght].ttf from the official google/fonts repo, pinned by commit and SHA-256.
// - Licence: SIL OFL 1.1. The font file stays in .cache/ (git-ignored). Only the outlined paths
//   go into the SVGs; the OFL allows this (artwork made with the font is not Font Software).
// - Layout copies brand/synthwerk-logo.svg: 46 px, weight 700, letter spacing -1.2 px,
//   baseline y = 63, x = 108 in the 400 × 96 lockup.
//
// Run: pnpm --filter @synthwerk/tokens wordmark   (needs network on the first run)
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'
import { type Primitive, primitives } from '../src/tokens.ts'

const COMMIT = '00a38a53f92aef923b9353f40128e8f4552ddae4'
const BASE = `https://raw.githubusercontent.com/google/fonts/${COMMIT}/ofl/spacegrotesk`
const FILES = {
  'SpaceGrotesk[wght].ttf': 'acad6de1fc93436f5c0f1f4137751ef04f1aea3063e7036535970ffcfbd79f72',
  'OFL.txt': '564ce565c371c5e5bbf286006565a7c9aa55a9f56e7ca58d56e05d649dd61a72'
} as const

const root = new URL('../', import.meta.url)
const cacheDir = fileURLToPath(new URL('.cache/fonts/', root))
const assetsDir = fileURLToPath(new URL('assets/', root))

async function download(name: keyof typeof FILES): Promise<Buffer> {
  const res = await fetch(`${BASE}/${encodeURIComponent(name)}`)
  if (!res.ok) throw new Error(`Download of ${name} failed: HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

const sha256 = (data: Buffer): string => createHash('sha256').update(data).digest('hex')

/** Returns the pinned file. A cached copy with a wrong hash is downloaded again once. */
async function fetchPinned(name: keyof typeof FILES): Promise<Buffer> {
  const path = cacheDir + name
  if (existsSync(path)) {
    const cached = readFileSync(path)
    if (sha256(cached) === FILES[name]) return cached
    rmSync(path)
  }
  const data = await download(name)
  const sha = sha256(data)
  if (sha !== FILES[name]) throw new Error(`${name}: SHA-256 ${sha} does not match the pin`)
  mkdirSync(cacheDir, { recursive: true })
  writeFileSync(path, data)
  return data
}

const WORD = 'synthwerk'
const SIZE = 46
const TRACKING_PX = -1.2
const BASELINE = 63
const WORD_X = 108

const hex = (p: Primitive): string => primitives[p]

interface Palette {
  readonly ink: string
  readonly from: string
  readonly to: string
}

const palettes: Record<'light' | 'dark', Palette> = {
  // Light surfaces: ink wordmark, print stops (≥ 3:1 on paper, WCAG 1.4.11).
  light: { ink: hex('zinc-950'), from: hex('print-cyan'), to: hex('print-magenta') },
  // Dark surfaces: paper wordmark, true neon stops.
  dark: { ink: hex('zinc-100'), from: hex('neon-cyan'), to: hex('neon-magenta') }
}

// Concept A "Patch" on the 48-unit grid (copied from brand/synthwerk-logo.svg).
const markShapes = (id: string, p: Palette): string =>
  [
    `<path d="M12 13h14a5.5 5.5 0 0 1 0 11h-4a5.5 5.5 0 0 0 0 11h14" fill="none" stroke="url(#${id})" stroke-width="5" stroke-linecap="round"/>`,
    `<circle cx="12" cy="13" r="5" fill="${p.from}"/>`,
    `<circle cx="36" cy="35" r="5" fill="${p.to}"/>`
  ].join('')

const gradient = (id: string, p: Palette): string =>
  `<defs><linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${p.from}"/><stop offset="1" stop-color="${p.to}"/></linearGradient></defs>`

const header = (comment: string): string =>
  `<!-- ${comment} Generated by packages/tokens/scripts/outline-wordmark.ts. Do not edit. -->\n`

const svg = (w: number, h: number, viewBox: string, title: string, body: string, comment: string) =>
  `${header(comment)}<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${w}" height="${h}" role="img" aria-label="${title}"><title>${title}</title>${body}</svg>\n`

async function main(): Promise<void> {
  const ttf = await fetchPinned('SpaceGrotesk[wght].ttf')
  await fetchPinned('OFL.txt')
  const font = opentype.parse(new Uint8Array(ttf).buffer)
  font.variation.set({ wght: 700 })

  // Lay out glyph by glyph: opentype.js 2.0.0 writes NaN into the path data when the
  // `letterSpacing` option is set, so the tracking is applied here instead.
  const scale = SIZE / font.unitsPerEm
  const glyphs = font.stringToGlyphs(WORD)
  const parts: string[] = []
  const box = {
    x1: Number.POSITIVE_INFINITY,
    y1: Number.POSITIVE_INFINITY,
    x2: -Infinity,
    y2: -Infinity
  }
  let x = WORD_X
  glyphs.forEach((glyph, i) => {
    const glyphPath = glyph.getPath(x, BASELINE, SIZE, { variation: { wght: 700 } }, font)
    parts.push(glyphPath.toPathData(2))
    const b = glyphPath.getBoundingBox()
    box.x1 = Math.min(box.x1, b.x1)
    box.y1 = Math.min(box.y1, b.y1)
    box.x2 = Math.max(box.x2, b.x2)
    box.y2 = Math.max(box.y2, b.y2)
    const next = glyphs[i + 1]
    const kern = next ? font.getKerningValue(glyph, next) : 0
    x += (glyph.advanceWidth + kern) * scale + TRACKING_PX
  })
  const d = parts.join('')
  if (!/^[MLQCZ0-9 .-]+$/.test(d))
    throw new Error('Wordmark path data is not finite (NaN in outline)')

  const credit =
    'Wordmark outlined from Space Grotesk Bold (SIL OFL 1.1, The Space Grotesk Project Authors).'
  mkdirSync(assetsDir, { recursive: true })

  for (const [mode, p] of Object.entries(palettes)) {
    // Horizontal lockup, 400 × 96 (same frame as the concept file).
    writeFileSync(
      `${assetsDir}synthwerk-logo-${mode}.svg`,
      svg(
        400,
        96,
        '0 0 400 96',
        'synthwerk',
        `${gradient(`sw-logo-${mode}`, p)}<g transform="scale(2)">${markShapes(`sw-logo-${mode}`, p)}</g><path fill="${p.ink}" d="${d}"/>`,
        `synthwerk lockup, ${mode} surfaces. ${credit}`
      )
    )
    // Wordmark only, tight box with 2 px padding.
    const pad = 2
    const x = Math.floor(box.x1) - pad
    const y = Math.floor(box.y1) - pad
    const w = Math.ceil(box.x2) + pad - x
    const h = Math.ceil(box.y2) + pad - y
    writeFileSync(
      `${assetsDir}synthwerk-wordmark-${mode}.svg`,
      svg(
        w,
        h,
        `${x} ${y} ${w} ${h}`,
        'synthwerk',
        `<path fill="${p.ink}" d="${d}"/>`,
        `synthwerk wordmark, ${mode} surfaces. ${credit}`
      )
    )
    // Mark only, 48-unit grid.
    writeFileSync(
      `${assetsDir}synthwerk-mark-${mode}.svg`,
      svg(
        48,
        48,
        '0 0 48 48',
        'synthwerk',
        `${gradient(`sw-mark-${mode}`, p)}${markShapes(`sw-mark-${mode}`, p)}`,
        `synthwerk mark, ${mode} surfaces.`
      )
    )
  }
  console.log(
    `assets written. Wordmark box: x ${box.x1.toFixed(1)}–${box.x2.toFixed(1)}, y ${box.y1.toFixed(1)}–${box.y2.toFixed(1)}`
  )
}

await main()
